import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "es" | "tr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

// Dil çevirileri
const translations = {
  tr: {
    // Genel
    "common.save": "Kaydet",
    "common.cancel": "İptal",
    "common.edit": "Düzenle",
    "common.delete": "Sil",
    "common.search": "Ara",
    "common.loading": "Yükleniyor...",
    "common.error": "Hata",
    "common.success": "Başarılı",
    "common.warning": "Uyarı",
    "common.info": "Bilgi",

    // Navigation
    "nav.dashboard": "Anasayfa",
    "nav.analytics": "Analitik",
    "nav.tables": "Tablolar",
    "nav.forms": "Form Sihirbazı",
    "nav.users": "Kullanıcılar",
    "nav.roles": "Roller",
    "nav.profile": "Profil",
    "nav.notifications": "Bildirimler",
    "nav.settings": "Ayarlar",
    "nav.login": "Giriş Yap",
    "nav.register": "Kayıt Ol",

    // Settings
    "settings.general": "Genel",
    "settings.profile": "Profil",
    "settings.notifications": "Bildirimler",
    "settings.security": "Güvenlik",
    "settings.appearance": "Görünüm",
    "settings.advanced": "Gelişmiş",
    "settings.appName": "Uygulama Adı",
    "settings.appDescription": "Uygulama ayarlarınızı ve tercihlerinizi yönetin",
    "settings.generalSettings": "Uygulama genel ayarlarını yapılandırın",
    "settings.language": "Dil",
    "settings.timezone": "Saat Dilimi",
    "settings.dateformat": "Tarih Formatı",
    "settings.automaticupdate": "Tarih Formatı",
    "settings.automaticupdate2": "Uygulama güncellemelerini otomatik olarak kontrol et",
    "settings.reporterror": "Hata Raporlama",
    "settings.sendreporterror": "Hata raporlarını geliştirici ekibine gönder",
    "settings.usagestadistics": "Kullanım İstatistikleri",
    "settings.usagesdata": "Anonim kullanım verilerini topla",
    "settings.theme": "Tema",
    "settings.light": "Açık",
    "settings.dark": "Koyu",
    "settings.system": "Sistem",
    "settings.colorScheme": "Renk Şeması",
    "settings.fontSize": "Yazı Tipi Boyutu",
    "settings.small": "Küçük",
    "settings.medium": "Orta",
    "settings.large": "Büyük",
    "settings.blue": "Mavi",
    "settings.green": "Yeşil",
    "settings.purple": "Mor",
    "settings.red": "Kırmızı",
    "settings.save": "Değişiklikleri Kaydet",
    "settings.cancel": "İptal",

    // Profile
    "profile.personalInfo": "Kişisel Bilgiler",
    "profile.contactInfo": "İletişim Bilgileri",
    "profile.skills": "Beceri ve Sertifikalar",
    "profile.activities": "Son Aktiviteler",
    "profile.editProfile": "Profili Düzenle",
    "profile.fullName": "Ad Soyad",
    "profile.email": "E-posta",
    "profile.phone": "Telefon",
    "profile.location": "Konum",
    "profile.bio": "Hakkında",
    "profile.company": "Şirket",
    "profile.position": "Pozisyon",
    "profile.department": "Departman",
    "profile.website": "Web Sitesi",
    "profile.configprofile": "Profil Ayarları",
    "profile.configprofile2": "Kişisel bilgilerinizi ve hesap ayarlarınızı güncelleyin",
    "profile.name": "Adı",
    "profile.secondname": "Göbek Adı",
    "profile.lastname": "Soyadı",
    "profile.surname": "Anne Adı",
    "profile.visibilityprofiletittle": "Profil Görünürlüğü",
    "profile.visibilityprofile": "Profilinizi diğer kullanıcılar görebilsin",

    // Notifications
    "notifications.all": "Tümü",
    "notifications.unread": "Okunmamış",
    "notifications.read": "Okunmuş",
    "notifications.markAllRead": "Tümünü Okundu İşaretle",
    "notifications.clearAll": "Tümünü Temizle",
    "notifications.noNotifications": "Bildirim bulunamadı",
    "notifications.last24Hours": "Son 24 Saat",
    "notifications.last7Days": "Son 7 Gün",
    "notifications.last30Days": "Son 30 Gün",
    "notifications.notificationsettings": "Bildirim Ayarları",
    "notifications.notificationpreferences": "Bildirim tercihlerinizi ve kanallarınızı yapılandırın",

    // Analytics
    "analytics.overview": "Genel Bakış",
    "analytics.visitors": "Ziyaretçiler",
    "analytics.revenue": "Gelir",
    "analytics.conversion": "Dönüşüm",
    "analytics.topPages": "En Popüler Sayfalar",
    "analytics.deviceDistribution": "Cihaz Dağılımı",
    "analytics.trafficSources": "Trafik Kaynakları",
    "analytics.title": "Analitik",
    "analytics.subtitle": "Detaylı performans analizi ve raporlar",
    "analytics.duration": "Süre",
    "analytics.7days": "7 gün",
    "analytics.30days": "30 gün",
    "analytics.90days": "90 gün",
    "analytics.1year": "1 yıl",
    "analytics.filter": "Filtrele",
    "analytics.downloadReport": "Rapor İndir",
    "analytics.totalVisitors": "Toplam Ziyaretçi",
    "analytics.pageViews": "Sayfa Görüntüleme",
    "analytics.conversionRate": "Dönüşüm Oranı",
    "analytics.avgSession": "Ortalama Oturum",
    "analytics.visitorTrend": "Ziyaretçi Trendi",
    "analytics.revenueAnalysis": "Gelir Analizi",
    "analytics.mobile": "Mobil",
    "analytics.desktop": "Desktop",
    "analytics.tablet": "Tablet",
    "analytics.homepage": "Anasayfa",
    "analytics.products": "Ürünler",
    "analytics.about": "Hakkımızda",
    "analytics.contact": "İletişim",
    "analytics.views": "görüntüleme",
    "analytics.bounce": "Bounce",
    "analytics.pageTitle": "Analitik",
    "analytics.metaDescription":
      "Detaylı analitik raporları ve performans metrikleri.",
    "analytics.jan": "Oca",
    "analytics.feb": "Şub",
    "analytics.mar": "Mar",
    "analytics.apr": "Nis",
    "analytics.may": "May",
    "analytics.jun": "Haz",

    // Dashboard
    "dashboard.welcome": "Hoş Geldin",
    "dashboard.totalUsers": "Toplam Kullanıcı",
    "dashboard.totalRevenue": "Toplam Gelir",
    "dashboard.activeProjects": "Aktif Projeler",
    "dashboard.pendingTasks": "Bekleyen Görevler",
    "dashboard.last30Days": "Son 30 günde",
    "dashboard.thisMonth": "Bu ay",
    "dashboard.ongoing": "Devam eden",
    "dashboard.pending": "Bekleyen",
    "dashboard.newUserRegistered": "Yeni kullanıcı kaydetti",
    "dashboard.projectUpdated": "Proje güncelledi",
    "dashboard.reportCreated": "Rapor oluşturdu",
    "dashboard.systemErrorReported": "Sistem hatası bildirdi",
    "dashboard.2minutesAgo": "2 dakika önce",
    "dashboard.15minutesAgo": "15 dakika önce",
    "dashboard.1hourAgo": "1 saat önce",
    "dashboard.3hoursAgo": "3 saat önce",
    "dashboard.addNewUser": "Yeni Kullanıcı Ekle",
    "dashboard.createReport": "Rapor Oluştur",
    "dashboard.startProject": "Proje Başlat",
    "dashboard.scheduleMeeting": "Toplantı Planla",
    "dashboard.recentActivities": "Son Aktiviteler",
    "dashboard.systemRecentOperations": "Sistemde gerçekleşen son işlemler",
    "dashboard.quickActions": "Hızlı İşlemler",
    "dashboard.frequentlyUsedOperations": "Sık kullanılan işlemler",
    "dashboard.projectStatus": "Proje Durumu",
    "dashboard.activeProjectsGeneralStatus": "Aktif projelerin genel durumu",
    "dashboard.ecommerceSite": "E-ticaret Sitesi",
    "dashboard.mobileApp": "Mobil Uygulama",
    "dashboard.adminPanel": "Admin Panel",
    "dashboard.systemStatus": "Sistem Durumu",
    "dashboard.serverAndServiceStatus": "Sunucu ve servis durumları",
    "dashboard.webServer": "Web Sunucu",
    "dashboard.database": "Veritabanı",
    "dashboard.apiService": "API Servisi",
    "dashboard.emailService": "E-posta Servisi",
    "dashboard.running": "Çalışıyor",
    "dashboard.error": "Hata",
    "dashboard.projectOverview":
      "Projenizin genel durumunu ve önemli metriklerini görüntüleyin",
    "dashboard.pageTitle": "Dashboard - React19 Admin",
    "dashboard.metaDescription": "Ana dashboard sayfası",
  },
  en: {
    // General
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.search": "Search",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.warning": "Warning",
    "common.info": "Info",

    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.analytics": "Analytics",
    "nav.tables": "Tables",
    "nav.forms": "Forms Wizard",
    "nav.users": "Users",
    "nav.roles": "Roles",
    "nav.profile": "Profile",
    "nav.notifications": "Notifications",
    "nav.settings": "Settings",
    "nav.login": "Login",
    "nav.register": "Register",

    // Settings
    "settings.general": "General",
    "settings.profile": "Profile",
    "settings.notifications": "Notifications",
    "settings.security": "Security",
    "settings.appearance": "Appearance",
    "settings.advanced": "Advanced",
    "settings.appName": "Application Name",
    "settings.appDescription": "Manage your app settings and preferences",
    "settings.generalSettings": "Configure application general settings",
    "settings.language": "Language",
    "settings.timezone": "Timezone",
    "settings.dateformat": "Date Format",
    "settings.automaticupdate": "Automatic Update",
    "settings.automaticupdate2": "Check for app updates automatically",
    "settings.reporterror": "Report Error",
    "settings.sendreporterror": "Send bug reports to the development team",
    "settings.usagestadistics": "Usage Statistics",
    "settings.usagesdata": "Collect anonymous usage data",
    "settings.theme": "Theme",
    "settings.light": "Light",
    "settings.dark": "Dark",
    "settings.system": "System",
    "settings.colorScheme": "Color Scheme",
    "settings.fontSize": "Font Size",
    "settings.small": "Small",
    "settings.medium": "Medium",
    "settings.large": "Large",
    "settings.blue": "Blue",
    "settings.green": "Green",
    "settings.purple": "Purple",
    "settings.red": "Red",
    "settings.save": "Save",
    "settings.cancel": "Cancel",

    // Profile
    "profile.personalInfo": "Personal Information",
    "profile.contactInfo": "Contact Information",
    "profile.skills": "Skills & Certifications",
    "profile.activities": "Recent Activities",
    "profile.editProfile": "Edit Profile",
    "profile.fullName": "Full Name",
    "profile.email": "Email",
    "profile.phone": "Phone",
    "profile.location": "Location",
    "profile.bio": "Bio",

    // Analytics
    "analytics.overview": "Overview",
    "analytics.visitors": "Visitors",
    "analytics.revenue": "Revenue",
    "analytics.conversion": "Conversion",
    "analytics.topPages": "Top Pages",
    "analytics.deviceDistribution": "Device Distribution",
    "analytics.trafficSources": "Traffic Sources",
    "analytics.title": "Analytics",
    "analytics.subtitle": "Detailed performance analysis and reports",
    "analytics.duration": "Duration",
    "analytics.7days": "7 days",
    "analytics.30days": "30 days",
    "analytics.90days": "90 days",
    "analytics.1year": "1 year",
    "analytics.filter": "Filter",
    "analytics.downloadReport": "Download Report",
    "analytics.totalVisitors": "Total Visitors",
    "analytics.pageViews": "Page Views",
    "analytics.conversionRate": "Conversion Rate",
    "analytics.avgSession": "Avg Session",
    "analytics.visitorTrend": "Visitor Trend",
    "analytics.revenueAnalysis": "Revenue Analysis",
    "analytics.mobile": "Mobile",
    "analytics.desktop": "Desktop",
    "analytics.tablet": "Tablet",
    "analytics.homepage": "Homepage",
    "analytics.products": "Products",
    "analytics.about": "About",
    "analytics.contact": "Contact",
    "analytics.views": "views",
    "analytics.bounce": "Bounce",
    "analytics.pageTitle": "Analytics",
    "analytics.metaDescription":
      "Detailed analytics reports and performance metrics.",
    "analytics.jan": "Jan",
    "analytics.feb": "Feb",
    "analytics.mar": "Mar",
    "analytics.apr": "Apr",
    "analytics.may": "May",
    "analytics.jun": "Jun",
    "profile.company": "Company",
    "profile.position": "Position",
    "profile.department": "Department",
    "profile.website": "Website",
    "profile.configprofile": "Profile Settings",
    "profile.configprofile2": "Update your personal information and account settings",
    "profile.name": "Name",
    "profile.secondname": "Middle Name",
    "profile.lastname": "Last Name",
    "profile.surname": "Surname",
    "profile.visibilityprofiletittle": "Profile Visibility",
    "profile.visibilityprofile": "Let other users see your profile",

    // Notifications
    "notifications.all": "All",
    "notifications.unread": "Unread",
    "notifications.read": "Read",
    "notifications.markAllRead": "Mark All as Read",
    "notifications.clearAll": "Clear All",
    "notifications.noNotifications": "No notifications found",
    "notifications.last24Hours": "Last 24 Hours",
    "notifications.last7Days": "Last 7 Days",
    "notifications.last30Days": "Last 30 Days",
    "notifications.notificationsettings": "Notification Settings",
    "notifications.notificationpreferences": "Configure your notification preferences and channels",

    // Dashboard
    "dashboard.welcome": "Welcome",
    "dashboard.totalUsers": "Total Users",
    "dashboard.totalRevenue": "Total Revenue",
    "dashboard.activeProjects": "Active Projects",
    "dashboard.pendingTasks": "Pending Tasks",
    "dashboard.last30Days": "Last 30 days",
    "dashboard.thisMonth": "This month",
    "dashboard.ongoing": "Ongoing",
    "dashboard.pending": "Pending",
    "dashboard.newUserRegistered": "Registered new user",
    "dashboard.projectUpdated": "Updated project",
    "dashboard.reportCreated": "Created report",
    "dashboard.systemErrorReported": "Reported system error",
    "dashboard.2minutesAgo": "2 minutes ago",
    "dashboard.15minutesAgo": "15 minutes ago",
    "dashboard.1hourAgo": "1 hour ago",
    "dashboard.3hoursAgo": "3 hours ago",
    "dashboard.addNewUser": "Add New User",
    "dashboard.createReport": "Create Report",
    "dashboard.startProject": "Start Project",
    "dashboard.scheduleMeeting": "Schedule Meeting",
    "dashboard.recentActivities": "Recent Activities",
    "dashboard.systemRecentOperations": "Recent operations in the system",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.frequentlyUsedOperations": "Frequently used operations",
    "dashboard.projectStatus": "Project Status",
    "dashboard.activeProjectsGeneralStatus":
      "General status of active projects",
    "dashboard.ecommerceSite": "E-commerce Site",
    "dashboard.mobileApp": "Mobile App",
    "dashboard.adminPanel": "Admin Panel",
    "dashboard.systemStatus": "System Status",
    "dashboard.serverAndServiceStatus": "Server and service statuses",
    "dashboard.webServer": "Web Server",
    "dashboard.database": "Database",
    "dashboard.apiService": "API Service",
    "dashboard.emailService": "Email Service",
    "dashboard.running": "Running",
    "dashboard.error": "Error",
    "dashboard.projectOverview":
      "View the general status and important metrics of your project",
    "dashboard.pageTitle": "Dashboard - React19 Admin",
    "dashboard.metaDescription": "Main dashboard page",
  },
  es: {
    // General
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
    "common.search": "Buscar",
    "common.loading": "Cargando...",
    "common.error": "Error",
    "common.success": "Éxito",
    "common.warning": "Advertencia",
    "common.info": "Información",

    // Navigation
    "nav.dashboard": "Panel",
    "nav.analytics": "Analítica",
    "nav.tables": "Tablas",
    "nav.forms": "Asistente de Formularios",
    "nav.users": "Usuarios",
    "nav.roles": "Roles",
    "nav.profile": "Perfil",
    "nav.notifications": "Notificaciones",
    "nav.settings": "Configuración",
    "nav.login": "Iniciar Sesión",
    "nav.register": "Registrarse",

    // Settings
    "settings.general": "General",
    "settings.profile": "Perfil",
    "settings.notifications": "Notificaciones",
    "settings.security": "Seguridad",
    "settings.appearance": "Apariencia",
    "settings.advanced": "Avanzado",
    "settings.appName": "Nombre de la aplicación",
    "settings.appDescription": "Administra la configuración y preferencias de tu aplicación",
    "settings.generalSettings": "Configurar los ajustes generales de la aplicación",
    "settings.language": "Idioma",
    "settings.timezone": "Zona horaria",
    "settings.dateformat": "Formato de fecha",
    "settings.automaticupdate": "Actualización automática",
    "settings.automaticupdate2": "Buscar actualizaciones de aplicaciones automáticamente",
    "settings.reporterror": "Informe de errores",
    "settings.sendreporterror": "Enviar informes de errores al equipo de desarrollo",
    "settings.usagestadistics": "Estadísticas de uso",
    "settings.usagesdata": "Recopilar datos de uso anónimos",
    "settings.theme": "Tema",
    "settings.light": "Claro",
    "settings.dark": "Oscuro",
    "settings.system": "Sistema",
    "settings.colorScheme": "Esquema de colores",
    "settings.fontSize": "Tamaño de fuente",
    "settings.small": "Pequeño",
    "settings.medium": "Mediano",
    "settings.large": "Grande",
    "settings.blue": "Azul",
    "settings.green": "Verde",
    "settings.purple": "Morado",
    "settings.red": "Rojo",
    "settings.save": "Guardar",
    "settings.cancel": "Cancelar",
    

    // Profile
    "profile.personalInfo": "Información Personal",
    "profile.contactInfo": "Información de Contacto",
    "profile.skills": "Habilidades y Certificaciones",
    "profile.activities": "Actividades Recientes",
    "profile.editProfile": "Editar Perfil",
    "profile.fullName": "Nombre Completo",
    "profile.email": "Correo Electrónico",
    "profile.phone": "Teléfono",
    "profile.location": "Ubicación",
    "profile.bio": "Biografía",
    "profile.company": "Empresa",
    "profile.position": "Puesto",
    "profile.department": "Departamento",
    "profile.website": "Sitio Web",
    "profile.configprofile": "Configuración del perfil",
    "profile.configprofile2": "Actualice su información personal y la configuración de su cuenta",
    "profile.name": "Primer nombre",
    "profile.secondname": "Segundo nombre",
    "profile.lastname": "Apellido paterno",
    "profile.surname": "Apellido materno",
    "profile.visibilityprofiletittle": "Visibilidad del perfil",
    "profile.visibilityprofile": "Permite que otros usuarios vean tu perfil",

    // Notificaciones
    "notifications.all": "Todas",
    "notifications.unread": "Sin leer",
    "notifications.read": "Leídas",
    "notifications.markAllRead": "Marcar todas como leídas",
    "notifications.clearAll": "Borrar todas",
    "notifications.noNotifications": "No se encontraron notificaciones",
    "notifications.last24Hours": "Últimas 24 horas",
    "notifications.last7Days": "Últimos 7 días",
    "notifications.last30Days": "Últimos 30 días",
    "notifications.notificationsettings": "Configuración de notificaciones",
    "notifications.notificationpreferences": "Configura tus preferencias y canales de notificación",

    // Analytics
    "analytics.overview": "Resumen",
    "analytics.visitors": "Visitantes",
    "analytics.revenue": "Ingresos",
    "analytics.conversion": "Conversión",
    "analytics.topPages": "Páginas Principales",
    "analytics.deviceDistribution": "Distribución por Dispositivo",
    "analytics.trafficSources": "Fuentes de Tráfico",
    "analytics.title": "Analítica",
    "analytics.subtitle": "Análisis detallado de rendimiento e informes",
    "analytics.duration": "Duración",
    "analytics.7days": "7 días",
    "analytics.30days": "30 días",
    "analytics.90days": "90 días",
    "analytics.1year": "1 año",
    "analytics.filter": "Filtrar",
    "analytics.downloadReport": "Descargar Informe",
    "analytics.totalVisitors": "Total de Visitantes",
    "analytics.pageViews": "Vistas de Página",
    "analytics.conversionRate": "Tasa de Conversión",
    "analytics.avgSession": "Duración Promedio de Sesión",
    "analytics.visitorTrend": "Tendencia de Visitantes",
    "analytics.revenueAnalysis": "Análisis de Ingresos",
    "analytics.mobile": "Móvil",
    "analytics.desktop": "Escritorio",
    "analytics.tablet": "Tableta",
    "analytics.homepage": "Página Principal",
    "analytics.products": "Productos",
    "analytics.about": "Acerca de",
    "analytics.contact": "Contacto",
    "analytics.views": "vistas",
    "analytics.bounce": "Rebote",
    "analytics.pageTitle": "Analítica",
    "analytics.metaDescription":
      "Informes detallados de analítica y métricas de rendimiento.",
    "analytics.jan": "Ene",
    "analytics.feb": "Feb",
    "analytics.mar": "Mar",
    "analytics.apr": "Abr",
    "analytics.may": "May",
    "analytics.jun": "Jun",

    // Dashboard
    "dashboard.welcome": "Bienvenido",
    "dashboard.totalUsers": "Usuarios Totales",
    "dashboard.totalRevenue": "Ingresos Totales",
    "dashboard.activeProjects": "Proyectos Activos",
    "dashboard.pendingTasks": "Tareas Pendientes",
    "dashboard.last30Days": "Últimos 30 días",
    "dashboard.thisMonth": "Este mes",
    "dashboard.ongoing": "En curso",
    "dashboard.pending": "Pendiente",
    "dashboard.newUserRegistered": "Nuevo usuario registrado",
    "dashboard.projectUpdated": "Proyecto actualizado",
    "dashboard.reportCreated": "Informe creado",
    "dashboard.systemErrorReported": "Error de sistema reportado",
    "dashboard.2minutesAgo": "Hace 2 minutos",
    "dashboard.15minutesAgo": "Hace 15 minutos",
    "dashboard.1hourAgo": "Hace 1 hora",
    "dashboard.3hoursAgo": "Hace 3 horas",
    "dashboard.addNewUser": "Agregar Nuevo Usuario",
    "dashboard.createReport": "Crear Informe",
    "dashboard.startProject": "Iniciar Proyecto",
    "dashboard.scheduleMeeting": "Programar Reunión",
    "dashboard.recentActivities": "Actividades Recientes",
    "dashboard.systemRecentOperations": "Operaciones recientes en el sistema",
    "dashboard.quickActions": "Acciones Rápidas",
    "dashboard.frequentlyUsedOperations": "Operaciones más usadas",
    "dashboard.projectStatus": "Estado del Proyecto",
    "dashboard.activeProjectsGeneralStatus":
      "Estado general de los proyectos activos",
    "dashboard.ecommerceSite": "Sitio de E-commerce",
    "dashboard.mobileApp": "Aplicación Móvil",
    "dashboard.adminPanel": "Panel de Administración",
    "dashboard.systemStatus": "Estado del Sistema",
    "dashboard.serverAndServiceStatus": "Estado de servidores y servicios",
    "dashboard.webServer": "Servidor Web",
    "dashboard.database": "Base de Datos",
    "dashboard.apiService": "Servicio API",
    "dashboard.emailService": "Servicio de Correo",
    "dashboard.running": "En ejecución",
    "dashboard.error": "Error",
    "dashboard.projectOverview":
      "Ver el estado general y métricas importantes de tu proyecto",
    "dashboard.pageTitle": "Panel - React19 Admin",
    "dashboard.metaDescription": "Página principal del panel de control",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "es";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    return (
      translations[language][
        key as keyof (typeof translations)[typeof language]
      ] || key
    );
  };

  const value = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
